### PR TITLE
Removed TODO

### PR DESCRIPTION
**Pull request by ConnorGBrewster**
r? @jspauldo98

### CODE REVIEW

**Comment by jspauldo98** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit b95161b has been approved by `jspauldo98`

**Comment by homu-salt** [comment]
:hourglass: Testing commit b95161b with merge b3a3e7b...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/jspauldo98/Salt/builds/128965669)

**Pull request merged**
