### PR TITLE
Build on PR

### PR DESCRIPTION
**Pull request by ConnorGBrewster**
I had to add master to the build whitelist so that PRs that should merge into master will be tested.

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit 03d140f has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit 03d140f with merge 0513ade...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/jspauldo98/Salt/builds/128753881)

**Pull request merged**
