### PR TITLE
Homu test2

### PR DESCRIPTION
**Pull request by ConnorGBrewster**

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@homu-salt try

**Comment by homu-salt** [comment]
:hourglass: Trying commit 5f2df07 with merge 457f504...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/jspauldo98/Salt/builds/128753084)

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit 5f2df07 has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit 5f2df07 with merge 7563496...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/jspauldo98/Salt/builds/128754167)

**Comment by homu-salt** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by homu-salt** [comment]
:pushpin: Commit 5f2df07 has been approved by `ConnorGBrewster`

**Comment by ConnorGBrewster** [comment]
@homu-salt retry

**Comment by homu-salt** [comment]
:hourglass: Testing commit 5f2df07 with merge 2987e89...

**Comment by ConnorGBrewster** [comment]
@homu-salt r-

**Pull request closed without merging**
