### PR TITLE
added object constructor

### PR DESCRIPTION
**Pull request by jspauldo98**

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit cf317d4 has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit cf317d4 with merge 4b62029...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/jspauldo98/Salt/builds/128730644)

**Pull request merged**
