### PR TITLE
delete object class

### PR DESCRIPTION
**Pull request by jspauldo98**

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@homu-salt r+
 * looks good

**Comment by homu-salt** [comment]
:pushpin: Commit c8d6030 has been approved by `ConnorGBrewster`

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- There's another pull request that is currently being tested, blocking this pull request: #13

**Comment by homu-salt** [comment]
:pushpin: Commit c8d6030 has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit c8d6030 with merge 1e9025e...

**Pull request merged**
